import type { Metadata } from "next";
import ReduxProvider from "../store/ReduxProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ReduxProvider>
        <body>
          {children}</body>
      </ReduxProvider>
    </html>
  );
}
